export const pieces: Piece[] = [
  {
    id: "1",
    name: "Cama unidade",
    qtde: 1,
    material: {
      id: "19",
      category: { id: "1", name: "MDF" },
      name: "Painel MDF 18mm",
      description:
        "Painel de MDF cru, espessura 18mm, dimensões 275x183cm, ideal para móveis e interiores.",
      measureType: "un",
      unit: "un",
      wasteTax: 0.05,
      baseValue: 120,
      measure: [503.25],
      code: "M-1249",
    },
  },
  {
    id: "1",
    name: "Cabeceira",
    qtde: 2,
    material: {
      id: "1",
      category: { id: "1", name: "MDF" },
      name: "Painel MDF 18mm",
      description:
        "Painel de MDF cru, espessura 18mm, dimensões 275x183cm, ideal para móveis e interiores.",
      measureType: "m2",
      unit: "cm",
      wasteTax: 0.05,
      baseValue: 120,
      measure: [200, 60],
      code: "M-1249",
    },
  },
  {
    id: "1",
    name: "Prateleira",
    qtde: 3,
    material: {
      id: "1",
      category: { id: "1", name: "MDF" },
      name: "Painel MDF 18mm",
      description:
        "Painel de MDF cru, espessura 18mm, dimensões 275x183cm, ideal para móveis e interiores.",
      measureType: "m2",
      unit: "cm",
      wasteTax: 0.05,
      baseValue: 120,
      measure: [100, 30],
      code: "M-1249",
    },
  },
  {
    id: "1",
    name: "Guarda-roupa",
    qtde: 1,
    material: {
      id: "2",
      category: { id: "2", name: "Compensado" },
      name: "Compensado Naval",
      description:
        "Compensado naval de 12mm, resistente à água, adequado para ambientes úmidos e projetos externos.",
      measureType: "m2",
      unit: "cm",
      wasteTax: 0.05,
      baseValue: 150,
      measure: [400],
      code: "M-1250",
    },
  },
  {
    id: "1",
    name: "Armário de Cozinha",
    qtde: 2,
    material: {
      id: "2",
      category: { id: "2", name: "Compensado" },
      name: "Compensado Naval",
      description:
        "Compensado naval de 12mm, resistente à água, adequado para ambientes úmidos e projetos externos.",
      measureType: "m2",
      unit: "cm",
      wasteTax: 0.05,
      baseValue: 150,
      measure: [180, 60],
      code: "M-1250",
    },
  },
];
