export const projectsSummaryList: Project[] = [
  {
    name: "Móveis do quarto de casal",
    qtde: 1,
    costs: [
      {
        name: "Equipe",
        qtde: 1,
        value: 120,
      },
    ],
    profitRate: 0.4,
    monthlyExpense: 0.1,
    comission: 0.3,
    pieces: [
      {
        id: "p1",
        name: "Cama",
        qtde: 1,
        material: {
          id: "m1",
          code: "MD001",
          category: { id: "c1", name: "Madeira" },
          name: "Madeira maciça",
          description: "Madeira de alta qualidade",
          measureType: "m2",
          unit: "cm",
          wasteTax: 0.05,
          baseValue: 800,
          measure: [200, 180],
        },
      },
      {
        id: "p2",
        name: "Guarda-roupa",
        qtde: 1,
        material: {
          id: "m2",
          code: "MD002",
          category: { id: "c1", name: "Madeira" },
          name: "MDF",
          description: "MDF 15mm",
          measureType: "m2",
          unit: "cm",
          wasteTax: 0.05,
          baseValue: 1500,
          measure: [250, 200],
        },
      },
    ],
  },
  {
    name: "Armários da cozinha",
    qtde: 1,
    costs: [
      {
        name: "Equipe",
        qtde: 1,
        value: 120,
      },
    ],
    profitRate: 0.4,
    monthlyExpense: 0.1,
    comission: 0.3,
    pieces: [
      {
        id: "p3",
        name: "Armário superior",
        qtde: 4,
        material: {
          id: "m2",
          code: "MD002",
          category: { id: "c1", name: "Madeira" },
          name: "MDF",
          description: "MDF 15mm",
          measureType: "m2",
          unit: "cm",
          wasteTax: 0.05,
          baseValue: 300,
          measure: [80, 60],
        },
      },
      {
        id: "p4",
        name: "Armário inferior",
        qtde: 4,
        material: {
          id: "m2",
          code: "MD002",
          category: { id: "c1", name: "Madeira" },
          name: "MDF",
          description: "MDF 15mm",
          measureType: "m2",
          unit: "cm",
          wasteTax: 0.05,
          baseValue: 400,
          measure: [80, 60],
        },
      },
    ],
  },
  {
    name: "Estante para livros",
    qtde: 1,
    costs: [
      {
        name: "Equipe",
        qtde: 1,
        value: 120,
      },
    ],
    profitRate: 0.4,
    monthlyExpense: 0.1,
    comission: 0.3,
    pieces: [
      {
        id: "p5",
        name: "Estante",
        qtde: 1,
        material: {
          id: "m3",
          code: "MD003",
          category: { id: "c2", name: "Compensado" },
          name: "Compensado naval",
          description: "Compensado de alta resistência",
          measureType: "m2",
          unit: "cm",
          wasteTax: 0.05,
          baseValue: 600,
          measure: [180, 80],
        },
      },
    ],
  },
];
