export const clients: Client[] = [
  {
    id: "1",
    code: "C-2394",
    name: "Maria do Carmo Almeida",
    note: "Cliente prefere entrega pela manhã, entre 8h e 10h",
    type: "pf",
    document: {
      type: "cpf",
      value: "123.456.789-00",
    },
    email: "maria.almeida@email.com",
    phone: "(11) 91234-5678",
    details: "Cliente antiga, sempre paga em dia",
    address: {
      street: "Rua das Flores, 123",
      neighborhood: "Centro",
      city: "São Paulo",
      cep: "01000-000",
    },
  },
  {
    id: "2",
    code: "C-6543",
    name: "José Roberto Madeiras Ltda",
    note: "Cliente prefere entrega pela manhã, entre 8h e 10h",
    type: "pj",
    document: {
      type: "cnpj",
      value: "12.345.678/0001-90",
    },
    email: "contato@madeirasltda.com",
    phone: "(11) 3344-5566",
    details: "Compra em grande volume, condições especiais de frete",
    address: {
      street: "Av. Paulista, 1500",
      neighborhood: "Bela Vista",
      city: "São Paulo",
      cep: "01310-200",
    },
  },
  {
    id: "3",
    code: "C-8943",
    name: "Eliane Souza Pereira",
    note: "Solicita que a entrega seja agendada sempre para às sextas-feiras",
    type: "pf",
    document: {
      type: "cpf",
      value: "987.654.321-00",
    },
    email: "elianesp@email.com",
    phone: "(21) 99876-5432",
    details: "Prefere contato por telefone",
    address: {
      street: "Rua do Mercado, 45",
      neighborhood: "Centro",
      city: "Rio de Janeiro",
      cep: "20010-120",
    },
  },
  {
    id: "4",
    code: "C-1234",
    name: "Moveis Delmar ME",
    note: "Aceita entrega apenas com nota fiscal impressa",
    type: "pj",
    document: {
      type: "cnpj",
      value: "23.456.789/0001-11",
    },
    email: "vendas@moveisdelmar.com",
    phone: "(41) 3322-7788",
    details: "Solicita sempre embalagens reforçadas",
    address: {
      street: "Rua XV de Novembro, 800",
      neighborhood: "Centro",
      city: "Curitiba",
      cep: "80020-310",
    },
  },
  {
    id: "5",
    code: "C-7433",
    name: "André Luiz Tavares",
    note: "Cliente costuma viajar, recomenda confirmar por WhatsApp antes",
    type: "pf",
    document: {
      type: "cpf",
      value: "321.654.987-00",
    },
    email: "andre.tavares@email.com",
    phone: "(31) 97777-8888",
    details: "Confirma sempre presença antes da entrega",
    address: {
      street: "Rua das Palmeiras, 250",
      neighborhood: "Savassi",
      city: "Belo Horizonte",
      cep: "30140-100",
    },
  },
  {
    id: "6",
    code: "C-0632",
    name: "MDF Pro Suprimentos Ltda",
    note: "Entregas somente de segunda a quinta, no horário comercial",
    type: "pj",
    document: {
      type: "cnpj",
      value: "34.567.890/0001-22",
    },
    email: "contato@mdfpro.com",
    phone: "(47) 3555-6677",
    details: "Exige conferência de nota fiscal eletrônica na entrega",
    address: {
      street: "Rodovia BR-101, Km 1200",
      neighborhood: "Industrial",
      city: "Joinville",
      cep: "89220-000",
    },
  },
  {
    id: "7",
    code: "C-2257",
    name: "Cláudia Ribeiro Fonseca",
    note: "Solicita que entregas sejam feitas na casa da mãe, endereço alternativo",
    type: "pf",
    document: {
      type: "cpf",
      value: "654.987.321-00",
    },
    email: "claudia.rf@email.com",
    phone: "(85) 98888-9999",
    details: "Prefere contato por e-mail",
    address: {
      street: "Rua das Acácias, 90",
      complement: "Casa da mãe",
      neighborhood: "Aldeota",
      city: "Fortaleza",
      cep: "60150-160",
    },
  },
];
