export const orders: Order[] = [
  {
    id: "P-03832",
    code: "C-3412",
    name: "Armário Planejado Quarto Casal",
    client: { id: "1", code: "C-3412", name: "Carla Ferreira" },
    status: "open",
    expirationDays: 30,
    initialDate: "2025-10-01",
    projects: [
      {
        name: "Projeto Principal",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 20,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 1000,
    deliveryDays: 15,
    paymentMethod: "credit",
    discountPercent: 0,
    installmentCount: 1,
    advanceAmount: 0,
    advancePaymentMethod: "to_agree",
    notes: "",
  },
  {
    id: "P-43436",
    code: "C-2289",
    name: "Cozinha Completa com Ilha Central",
    client: { id: "2", code: "C-2289", name: "Felipe Rocha" },
    status: "approved",
    expirationDays: 30,
    initialDate: "2025-09-20",
    projects: [
      {
        name: "Projeto Cozinha",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 25,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 5000,
    deliveryDays: 20,
    paymentMethod: "pix",
    discountPercent: 5,
    installmentCount: 2,
    advanceAmount: 1000,
    advancePaymentMethod: "bank_transfer",
    notes: "",
  },
  {
    id: "P-98543",
    code: "C-7771",
    name: "Estante Sob Medida para Escritório",
    client: { id: "3", code: "C-7771", name: "Escritório Ana Lima" },
    status: "open",
    expirationDays: 30,
    initialDate: "2025-10-05",
    projects: [
      {
        name: "Projeto Estante",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 18,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 1500,
    deliveryDays: 10,
    paymentMethod: "debit",
    discountPercent: 0,
    installmentCount: 1,
    advanceAmount: 0,
    advancePaymentMethod: "to_agree",
    notes: "",
  },
  {
    id: "P-13345",
    code: "C-5120",
    name: "Guarda-Roupas Infantil com Nichos",
    client: { id: "4", code: "C-5120", name: "Diego Amaral" },
    status: "open",
    expirationDays: 30,
    initialDate: "2025-10-07",
    projects: [
      {
        name: "Projeto Guarda-Roupas",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 22,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 2000,
    deliveryDays: 12,
    paymentMethod: "credit",
    discountPercent: 0,
    installmentCount: 1,
    advanceAmount: 500,
    advancePaymentMethod: "pix",
    notes: "",
  },
  {
    id: "P-85332",
    code: "C-0981",
    name: "Closet com Portas de Correr",
    client: { id: "5", code: "C-0981", name: "Marisa Silva" },
    status: "approved",
    expirationDays: 30,
    initialDate: "2025-09-30",
    projects: [
      {
        name: "Projeto Closet",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 20,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 3500,
    deliveryDays: 18,
    paymentMethod: "bank_transfer",
    discountPercent: 5,
    installmentCount: 2,
    advanceAmount: 1000,
    advancePaymentMethod: "pix",
    notes: "",
  },
  {
    id: "P-66321",
    code: "C-3344",
    name: "Painel para TV com Iluminação LED",
    client: { id: "6", code: "C-3344", name: "Jorge Batista" },
    status: "open",
    expirationDays: 30,
    initialDate: "2025-10-10",
    projects: [
      {
        name: "Projeto Painel",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 15,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 1200,
    deliveryDays: 10,
    paymentMethod: "debit",
    discountPercent: 0,
    installmentCount: 1,
    advanceAmount: 0,
    advancePaymentMethod: "to_agree",
    notes: "",
  },
  {
    id: "P-55895",
    code: "C-4532",
    name: "Armário Suspenso para Lavanderia",
    client: { id: "7", code: "C-4532", name: "Bruno Teixeira" },
    status: "open",
    expirationDays: 30,
    initialDate: "2025-10-11",
    projects: [
      {
        name: "Projeto Lavanderia",
        qtde: 1,
        pieces: [],
        costs: [],
        profitRate: 18,
        monthlyExpense: 0,
        comission: 0,
      },
    ],
    included: "Incluso padrão",
    excluded: "Excluído padrão",
    teamNotes: "",
    rawAmount: 900,
    deliveryDays: 8,
    paymentMethod: "credit",
    discountPercent: 0,
    installmentCount: 1,
    advanceAmount: 0,
    advancePaymentMethod: "to_agree",
    notes: "",
  },
];
