export const materials: Material[] = [
  {
    id: "1",
    category: { id: "1", name: "MDF" },
    name: "Painel MDF 18mm",
    description:
      "Painel de MDF cru, espessura 18mm, dimensões 275x183cm, ideal para móveis e interiores.",
    measureType: "m2",
    unit: "cm",
    wasteTax: 0.05,
    baseValue: 120,
    measure: [503.25, 44],
    code: "M-1249",
  },
  {
    id: "2",
    category: { id: "2", name: "Compensado" },
    name: "Compensado Naval",
    description:
      "Compensado naval de 12mm, resistente à água, adequado para ambientes úmidos e projetos externos.",
    measureType: "m2",
    unit: "cm",
    wasteTax: 0.05,
    baseValue: 150,
    measure: [400],
    code: "M-1250",
  },
  {
    id: "3",
    category: { id: "3", name: "Ferragens" },
    name: "Dobradiça 35mm",
    description:
      "Dobradiça metálica de 35mm para portas e móveis, garantindo abertura suave e durabilidade.",
    measureType: "un",
    unit: "un",
    wasteTax: 0.02,
    baseValue: 5,
    measure: [1],
    code: "M-1251",
  },
  {
    id: "4",
    category: { id: "4", name: "Material de consumo" },
    name: "Parafuso 4x40mm",
    description:
      "Parafuso zincado 4x40mm, resistente à corrosão, ideal para fixação em madeira.",
    measureType: "un",
    unit: "un",
    wasteTax: 0.02,
    baseValue: 0.5,
    measure: [1],
    code: "M-1252",
  },
  {
    id: "5",
    category: { id: "5", name: "Fita de borda" },
    name: "Fita de borda PVC",
    description:
      "Fita de borda em PVC branca de 22mm, para acabamento de móveis e painéis.",
    measureType: "ml",
    unit: "cm",
    wasteTax: 0.05,
    baseValue: 1.5,
    measure: [100],
    code: "M-1253",
  },
];
